parameters: {}
environment: {}  # TODO: secret API keys for authenticating to Postgres and DO will populate here

packages:
    - name: inference
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello  # change to "run" later. Just testing for now.
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}

          # schedule the function to run every day
          triggers:
            - name: trigger-inference-every-day
              sourceType: scheduler
              sourceDetails:
                cron: "0 0 * * *"  # every day at midnight UTC
