environment:
    TAIMAKA_DO_ACCESS_KEY: "${TAIMAKA_DO_ACCESS_KEY}"
    TAIMAKA_DO_SECRET_KEY: "${TAIMAKA_DO_SECRET_KEY}"

packages:
    - name: inference
      functions:
        - name: run
          main: ""
          runtime: python:3.11
          web: true
