name: unit test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pandas
          #pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests/
